export const data = [
  {
    id: 1,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
  {
    id: 2,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
  {
    id: 3,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
  {
    id: 4,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
  {
    id: 5,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
  {
    id: 6,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
  {
    id: 7,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
  {
    id: 8,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
  {
    id: 9,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
  {
    id: 10,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
  {
    id: 11,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
  {
    id: 12,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
  {
    id: 13,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
  {
    id: 14,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
  {
    id: 15,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
  {
    id: 16,
    name: "우리회사",
    image: "./image/company.jpg",
    category: "펫",
    info: "펫을 키우는 키우는 키우는 회사 입니다.",
    location: "강남",
  },
];
